"""product category fk ondelete set null

Revision ID: 65e03853b184
Revises: b72862e0a259
Create Date: 2026-09-08 09:42:51.083432

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '65e03853b184'
down_revision: str | None = 'b72862e0a259'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
